name: Validate Commit Messages

# Trigger this workflow on every push
on: push

jobs:
  validate-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate commit messages
        run: |
          echo "Validating commit messages..."
          
          # Fetch the commits in the push
          commits=$(git rev-list ${{ github.event.before }}..${{ github.sha }})

          for commit in $commits; do
            # Extract the commit message
            message=$(git log -1 --format=%B $commit)

            # Validate against the ticket regex
            if ! [[ "$message" =~ ^PROJ-[0-9]+ ]]; then
              echo "Invalid commit message: '$message'"
              echo "Commit messages must include a valid ticket number (e.g., PROJ-1)."
              exit 1
            fi
          done

          echo "All commit messages are valid!"
